# Generated by Django 2.0.7 on 2018-07-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='md5',
            name='md5',
        ),
        migrations.AddField(
            model_name='md5',
            name='file_pdf_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='file_pdf_address'),
        ),
        migrations.AddField(
            model_name='md5',
            name='file_pdf_md5',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='file_pdf_md5'),
        ),
        migrations.AddField(
            model_name='md5',
            name='file_source_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='file_source_name'),
        ),
        migrations.AddField(
            model_name='md5',
            name='file_source_md5',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='file_source_md5'),
        ),
    ]
