# Generated by Django 2.0.7 on 2018-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0002_auto_20180731_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='md5',
            name='file_pdf_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_pdf_address'),
        ),
        migrations.AlterField(
            model_name='md5',
            name='file_source_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_source_name'),
        ),
    ]
