version: '3'
services:
    transcode:
        image: slzcc/transcode:0.4.0
        container_name: transcode
        ports:
          - 8089:8089
            TZ: Asia/Shanghai
        hostname: "example.org"

        hostname: "example.org"
        volumes:
          - ../TranscodePDF:/TranscodePDF