version: '3'
services:
    transcode:
        image: slzcc/transcode:0.3.12
        container_name: transcode
        ports:
          - 8089:8089
        environment:
            MYSQL_DATABASE: resumec
            MYSQL_USER: resumec
            MYSQL_PASSWORD: resumec
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: example.org
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            NGINX_MIRROR_ADDRESS: "http://47.95.219.151/"
            TZ: Asia/Shanghai
            # Non-generic function
            NGF: "False"
            NGF_PROXY_ADDRESS_1: "218.240.137.68:8093"
            NGF_PROXY_ADDRESS_1: "cats.hydsoft.com:8093"
            NGF_TARGET_ADDRESS: "192.168.114.17:8080"
        hostname: "example.org"
        depends_on:
           - mysql
    mysql:
        image: slzcc/mysql:5.6-custom
        environment:
            MYSQL_ROOT_PASSWORD: example.org
            MYSQL_DATABASE: resumec
            MYSQL_USER: resumec
            MYSQL_PASSWORD: resumec
            TZ: Asia/Shanghai
        container_name: transcode-mysql
        volumes:
          - mysql:/var/lib/mysql:rw
volumes:
    mysql: