version: '3'
services:
    transcode:
        image: slzcc/django:transcode-pdf-uwsgi-v4
        container_name: transcode
        ports:
          - 8089:8089
        environment:
            MYSQL_DATABASE: check_md5
            MYSQL_USER: check_md5
            MYSQL_PASSWORD: check_md5
            MYSQL_HOST: "mysql"
            MYSQL_PORT: 3306
            NGINX_MIRROR_ADDRESS: "http://47.95.219.151/"
            TZ: Asia/Shanghai
        hostname: "example.org"
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: example.org
            MYSQL_DATABASE: check_md5
            MYSQL_USER: check_md5
            MYSQL_PASSWORD: check_md5
            TZ: Asia/Shanghai
        container_name: transcode-mysql
        volumes:
          - mysql:/var/lib/mysql:rw
volumes:
    mysql:
